version: '3.8'
services:
  postgres:
    image: postgres:13.1
    container_name: db
    environment:
      - POSTGRES_USER=sua
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=stock_price
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - type: volume
        source: stock-db
        target: /var/lib/postgresql/data
    networks:
      - stock-network
      
  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - type: volume
        source: stock-jenkins
        target: /var/jenkins_home
    networks:
      - stock-network
      
  batch-server:
    container_name: batch-server
    build:
      context: ./stock-batch
      dockerfile: Dockerfile
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}
    image: stock-batch:latest
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - crawl-server
    networks:
      - stock-network
    volumes:
      - type: volume
        source: stock-buffer
        target: /opt/stock-crawling/data

  web-server:
    container_name: web-server
    build:
      context: ./stock-web
      dockerfile: Dockerfile
    image: stock-web:latest
    stdin_open: true
    tty: true
    ports:
      - 9999:8080
    expose:
      - "9999"
    depends_on:
      - postgres
    networks:
      - stock-network
  
  crawl-server:
    container_name: crawl-server
    build:
      context: ./stock-crawler
      dockerfile: Dockerfile
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}
    image: stock-crawler:latest
    stdin_open: true
    tty: true
    network:
      - stock-network
    volumes:
      - type: volume
        source: stock-buffer
        target: /home/jenkins/data


networks:
  stock-network:
    driver: bridge
volumes:
  stock-db:
  stock-buffer:
  stock-jenkins:
