spring:
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stock_price
    username: sua
    password: psql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #jdbc:
        # batch_size: 100
        show_sql: false
        generate_statistics: false
      #      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      open-in-view: false
      show-sql: false
input.file.name: /Users/sua/Github/project/stock-crawling/stock-data/example.csv
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: info

---
spring:
  profiles:
    active: default
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/stock_price
input.file.name: /opt/stock-crawling/data/example.csv
---